# Generated by Django 4.2.29 on 2026-03-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ürün Adı')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyatı')),
                ('stock', models.IntegerField(verbose_name='Stok Adedi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
