# Generated by Django 4.2.11 on 2026-03-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateTimeField(auto_now_add=True, verbose_name='Satış Tarihi')),
                ('district', models.CharField(choices=[('Besiktas', 'Beşiktaş'), ('Kadikoy', 'Kadıköy'), ('Umraniye', 'Ümraniye'), ('Fatih', 'Fatih'), ('Esenyurt', 'Esenyurt'), ('Sariyer', 'Sarıyer')], default='Besiktas', max_length=50, verbose_name='İstanbul Semti')),
                ('products', models.ManyToManyField(to='myapp.product', verbose_name='Satılan Ürünler')),
            ],
        ),
    ]
