# Generated by Django 4.2.11 on 2026-03-23 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_product_price_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='Genel', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='sale',
            name='district',
            field=models.CharField(choices=[('Adalar', 'Adalar'), ('Arnavutkoy', 'Arnavutköy'), ('Atasehir', 'Ataşehir'), ('Avcilar', 'Avcılar'), ('Bagcilar', 'Bağcılar'), ('Bahcelievler', 'Bahçelievler'), ('Bakirkoy', 'Bakırköy'), ('Basaksehir', 'Başakşehir'), ('Bayrampasa', 'Bayrampaşa'), ('Besiktas', 'Beşiktaş'), ('Beykoz', 'Beykoz'), ('Beylikduzu', 'Beylikdüzü'), ('Beyoglu', 'Beyoğlu'), ('Buyukcekmece', 'Büyükçekmece'), ('Catalca', 'Çatalca'), ('Cekmekoy', 'Çekmeköy'), ('Esenler', 'Esenler'), ('Esenyurt', 'Esenyurt'), ('Eyupsultan', 'Eyüpsultan'), ('Fatih', 'Fatih'), ('Gaziosmanpasa', 'Gaziosmanpaşa'), ('Gungoren', 'Güngören'), ('Kadikoy', 'Kadıköy'), ('Kagithane', 'Kağıthane'), ('Kartal', 'Kartal'), ('Kucukcekmece', 'Küçükçekmece'), ('Maltepe', 'Maltepe'), ('Pendik', 'Pendik'), ('Sancaktepe', 'Sancaktepe'), ('Sariyer', 'Sarıyer'), ('Silivri', 'Silivri'), ('Sultanbeyli', 'Sultanbeyli'), ('Sultangazi', 'Sultangazi'), ('Sile', 'Şile'), ('Sisli', 'Şişli'), ('Tuzla', 'Tuzla'), ('Umraniye', 'Ümraniye'), ('Uskudar', 'Üsküdar'), ('Zeytinburnu', 'Zeytinburnu')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sale',
            name='products',
            field=models.ManyToManyField(to='myapp.product'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
