# Generated by Django 4.2.11 on 2026-03-23 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_product_created_at_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='sale',
            name='shop_name',
            field=models.CharField(default='Merkez Market', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sale',
            name='district',
            field=models.CharField(max_length=50),
        ),
    ]
