# Generated by Django 4.2.11 on 2026-03-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_product_stock_sale_shop_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='sale_date',
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='sale',
            name='lat',
            field=models.FloatField(default=41.0082),
        ),
        migrations.AddField(
            model_name='sale',
            name='lng',
            field=models.FloatField(default=28.9784),
        ),
        migrations.AlterField(
            model_name='sale',
            name='district',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sale',
            name='shop_name',
            field=models.CharField(max_length=100),
        ),
    ]
