# Generated by Django 4.2.11 on 2026-03-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_sale_sale_date_product_stock_sale_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=10),
        ),
    ]
