# Generated by Django 4.2.11 on 2026-03-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_discounted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='recommendation',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
