# Generated by Django 4.2.11 on 2026-03-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_product_is_discounted_sale_recommendation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_discounted',
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.CharField(default='https://via.placeholder.com/150', max_length=500),
        ),
    ]
