# Generated by Django 4.2.11 on 2026-03-31 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_product_is_discounted_product_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='district',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
